coeur_1: [1, 11]
coeur_2: [2]
coeur_3: [3]
coeur_4: [4]
coeur_5: [5]
coeur_6: [6]
coeur_7: [7]
coeur_8: [8]
coeur_9: [9]
coeur_10: [10]
coeur_jack: [10]
coeur_queen: [10]
coeur_king: [10]

diamond_1: [1, 11]
diamond_2: [2]
diamond_3: [3]
diamond_4: [4]
diamond_5: [5]
diamond_6: [6]
diamond_7: [7]
diamond_8: [8]
diamond_9: [9]
diamond_10: [10]
diamond_jack: [10]
diamond_queen: [10]
diamond_king: [10]

spade_1: [1, 11]
spade_2: [2]
spade_3: [3]
spade_4: [4]
spade_5: [5]
spade_6: [6]
spade_7: [7]
spade_8: [8]
spade_9: [9]
spade_10: [10]
spade_jack: [10]
spade_queen: [10]
spade_king: [10]

clover_1: [1, 11]
clover_2: [2]
clover_3: [3]
clover_4: [4]
clover_5: [5]
clover_6: [6]
clover_7: [7]
clover_8: [8]
clover_9: [9]
clover_10: [10]
clover_jack: [10]
clover_queen: [10]
coeur_king: [10]
