get_blackjack_homepage:
    path:     /
    defaults: { _controller: CasinoBlackjackBundle:Player:index }
    requirements:
        _method:  GET

get_blackjack_login:
    path:     /login
    defaults: { _controller: CasinoBlackjackBundle:Player:login }
    requirements:
        _method:  GET

post_blackjack_login:
    path:     /login
    defaults: { _controller: CasinoBlackjackBundle:Player:createPlayer }
    requirements:
        _method:  POST

blackjack_start_game:
    path:     /game/start
    defaults: { _controller: CasinoBlackjackBundle:Game:start }
    requirements:
        _method:  GET

blackjack_start_round:
    path:     /game/round/start
    defaults: { _controller: CasinoBlackjackBundle:Game:startRound }
    requirements:
        _method:  GET

blackjack_game:
    path:     /game
    defaults: { _controller: CasinoBlackjackBundle:Game:play }
    requirements:
        _method:  GET

blackjack_bet:
    path:     /game/bet
    defaults: { _controller: CasinoBlackjackBundle:Game:bet }
    requirements:
        _method:  POST

blackjack_playerDraw:
    path:     /game/draw
    defaults: { _controller: CasinoBlackjackBundle:Game:playerDraw }
    requirements:
        _method:  POST

blackjack_dealerDraw:
    path:     /game/dealer
    defaults: { _controller: CasinoBlackjackBundle:Game:dealerDraw }
    requirements:
        _method:  POST

blackjack_end_round:
    path:     /game/round/end
    defaults: { _controller: CasinoBlackjackBundle:Game:end }
    requirements:
        _method:  GET

get_stats:
    path:     /stats
    defaults: { _controller: CasinoBlackjackBundle:Info:getStats }
    requirements:
        _method:  GET

get_player_page:
    path:     /player/{playerId}
    defaults: { _controller: CasinoBlackjackBundle:Player:profile }
    requirements:
        _method:  GET