<?php

namespace Casino\BlackjackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RevealedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RevealedRepository extends EntityRepository
{
    public function findNamesByRoundId($roundId)
    {
        return $this->getEntityManager()
                    ->createQuery(
                        'SELECT rev.name FROM CasinoBlackjackBundle:Revealed rev
                        JOIN rev.round r
                        WHERE r.id = :id'
                    )
                    ->setParameter('id', $roundId)
                    ->getResult();
    }

    public function findPlayerCards($roundId)
    {
        return $this->getEntityManager()
                    ->createQuery(
                        "SELECT rev FROM CasinoBlackjackBundle:Revealed rev
                        JOIN rev.round r
                        WHERE r.id = :id
                        AND rev.playerType = 'player'"
                    )
                    ->setParameter('id', $roundId)
                    ->getResult();
    }

    public function findDealerCards($roundId)
    {
        return $this->getEntityManager()
                    ->createQuery(
                        "SELECT rev FROM CasinoBlackjackBundle:Revealed rev
                        JOIN rev.round r
                        WHERE r.id = :id
                        AND rev.playerType = 'dealer'"
                    )
                    ->setParameter('id', $roundId)
                    ->getResult();
    }
}
